[linters]
enable = [
  "copyloopvar",
  "dogsled",
  "forcetypeassert",
  "goconst",
  "gocritic",
  "gocyclo",
  "goimports",
  "goprintffuncname",
  "gosimple",
  "govet",
  "ineffassign",
  "misspell",
  "nakedret",
  "revive",
  "staticcheck",
  "stylecheck",
  "typecheck",
  "unconvert",
  "unparam",
  "unused",
  "whitespace"
]
