name: Benchstat

on: [pull_request]

jobs:
  incoming:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Benchmark
        run: go test ./... -count=2 -run=Benchmark -bench=. | tee -a bench.txt
      - name: Upload Benchmark
        uses: actions/upload-artifact@v3
        with:
          name: bench-incoming
          path: bench.txt
  current:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Benchmark
        run: go test ./... -count=2 -run=Benchmark -bench=. | tee -a bench.txt
      - name: Upload Benchmark
        uses: actions/upload-artifact@v3
        with:
          name: bench-current
          path: bench.txt
  benchstat:
    needs: [incoming, current]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest
      - name: Download Incoming
        uses: actions/download-artifact@v3
        with:
          name: bench-incoming
          path: bench-incoming.txt
      - name: Download Current
        uses: actions/download-artifact@v3
        with:
          name: bench-current
          path: bench-current.txt
      - run: ls -R
      - name: Benchstat Results
        run: benchstat bench-current.txt bench-incoming.txt | tee -a benchstat.txt
      - name: Upload benchstat results
        uses: actions/upload-artifact@v3
        with:
          name: benchstat
          path: benchstat.txt
      - name: Comment on PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: benchstat.txt