name: jsonnetfmt
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  jsonnetfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod
      - name: Format
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
          ./scripts/jsonnetfmt.sh
      - run: |
          STATUS="$(git status --porcelain)"
          test -z "${STATUS}" || {
            echo "Found changes after formatting. Run jsonnetfmt on the following files:"
            echo "${STATUS}"
            exit 1
          }
