name: jsonnetfmt
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  jsonnetfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Format
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
          ./scripts/jsonnetfmt.sh
      - run: |
          STATUS="$(git status --porcelain)"
          test -z "${STATUS}" || {
            echo "Found changes after formatting. Run jsonnetfmt on the following files:"
            echo "${STATUS}"
            exit 1
          }
